config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "messages#index"
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates :english_message, presence: true, length: { maximum: 25 }
  validates :morse_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all.sort_by(&:created_at).reverse
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to messages_path, notice: 'Message was successfully created.'
    else
      render :new, alert: 'Message was not created.', status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:english_message, :morse_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enigma</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<p>Count of messages: <%= @messages.count %></p>
<ul class="messages_list">
  <% @messages.each do |message| %>
    <li class="message">
      <span>
        <%= message.english_message %> 
      </span>
      <span>
        <%= message.morse_code %>
      </span>
    </li>  
  <% end %>
</ul>

app/views/messages/new.html.erb
<%= form_for @message do |f| %>
  <%= f.text_field :english_message, placeholder: "Enter your message" %>
  <% @message.errors.full_messages_for(:english_message).each do |message| %>
    <div><%= message %></div>
  <% end %>

  <%= f.text_field :morse_code, placeholder: "Enter your message" %>
  <% @message.errors.full_messages_for(:morse_code).each do |message| %>
    <div><%= message %></div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <h1>Enigma Machine</h1>
  <div class="left">
    <h2><%= link_to "All" , root_path, class: ('active' if current_page?(root_path)) %></h2>
    <h2><%= link_to "New" , new_message_path, class: ('active' if current_page?(new_message_path)) %></h2>
  </div>
</nav>